console.log(true*"true");
// nan
console.log(true+"true")
// return truetrue
console.log(true-"true")
console.log(true%"true")
console.log(true/"true")
console.log(1+undefined);
// NAN
console.log(undefined+null)
// NAN
console.log(undefined*null)
// NAN
console.log(undefined%null)
// NAN
console.log(undefined/null)
console.log(1+undefined)
// NAN
console.log(false+false+false+true+undefined)
// nan
// NAN
// JAVASCRIPT ONLY CHECK VALUE (NULL)(0) WHERE AS UNDEFINED(NAN)
// error
// console.log(2--+"string")
// console.log(--2++"string")

